config/routes.rb
Rails.application.routes.draw do
  get 'events/new'
  get 'events/index'
  get '/' => 'planners#new'
  post 'planner/create' => 'planners#create'
  post 'event/create' => 'events#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :planner, class_name: "Planner", foreign_key: "planner_id"
end

app/models/planner.rb
class Planner < ApplicationRecord
  has_secure_password
  has_many :events, class_name: "Event"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def index
    @events = Event.all
  end

  def create
    @planner = Planner.find_by(id: session[:planner_id])
    @event = @planner.events.build(event_params)
    p "====================="
    p @event
    p "====================="
    if @event.save
      redirect_to "events/index"
    else
      render :new
    end
  end

  private
    def event_params
      params.require(:event).permit(:name, :prefecture, :address1)
    end
end

app/controllers/planners_controller.rb
class PlannersController < ApplicationController
  def new
    @planner = Planner.new
  end

  def create
    @planner = Planner.new(planner_params)
    if @planner.save
      session[:planner_id] = @planner.id
      redirect_to "/"
    else
      render :new
    end
  end

  private
    def planner_params
      params.require(:planner).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/planners_helper.rb
module PlannersHelper
end

app/views/events/index.html.erb
<% if session[:planner_id] %>
<h1>Events#index</h1>
<p>Find me in app/views/events/index.html.erb</p>
<% @events.each do |event| %>
  <%= event.name %><br/>
<% end %>

<% else %>
  ログインしてください
  <%= link_to "ログインして", "/" %>
<% end %>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>
<%= form_for @event, url: event_create_path do |f| %>
  <%= f.text_field :name %>
  <input type="text" id="postal" onKeyUp="$('#postal').zip2addr('#event_prefecture', '#event_address1');" ><br>
  <input type="text" id="event_prefecture" name="event[prefecture]" ><br>
  <input type="text" id="event_address1" name="event[address1]">
  <%= f.submit %>
<% end %>

<script>
/*
 * jQuery.zip2addr
 *
 * Copyright 2010, Kotaro Kokubo a.k.a kotarok kotaro@nodot.jp
 * Dual licensed under the MIT or GPL Version 2 licenses.
 *
 * https://github.com/kotarok/jQuery.zip2addr
 *
 * Depends:
 *	jQuery 1.4 or above
 */

$.fn.zip2addr = function(target, target1) {
  var c = {
    api: 'http://www.google.com/transliterate?langpair=ja-Hira|ja&jsonp=?',
    prefectureToken: '(東京都|道|府|県)',
    zipDelimiter: '-'
  }

  var cache = $.fn.zip2addr.cache;

  var getAddr = function(zip, callback) {
    $.getJSON(c.api, {
        'text': zip
      },
      function(json) {
        if (RegExp(c.prefectureToken).test(json[0][1][0])) {
          callback(json[0][1][0].replace(RegExp('(.*?' + c.prefectureToken + ')(.+)'), function(a, b, c, d) {
            return [b, d]
          }))
        }
      }
    )
  }

  var fillAddr = (function() {
    if (typeof target1 == 'object' && target1.pref) {
      return function(addr) {
        var addrs = addr.split(',');
        if (addrs) {
          if (!RegExp(addrs[1]).test($(target1.addr).val())) {
            $(target1.pref).val(addrs[0]);
            $(target1.addr).val(addrs[1]);
          }
        } else if (!RegExp(addrs[1]).test($(target1.addr).val())) {
          $(target1.pref).add(target1.addr).val('');
        }
      }
    } else {
      return function(addr) {
        var addrs = addr.split(',');
        var addrStr = addr.replace(',', '');
        var addrField = target1.addr || target1;
        if (addrStr) {
          if (!RegExp(addrStr).test($(addrField).val())) {
            $(target).val(addrs[0]);
            $(addrField).val(addrs[1]);
          }
        } else if (!RegExp(addrStr).test($(addrField).val())) {
          $(addrField).val('');
        }
      }
    }
  })()

  //From http://liosk.blog103.fc2.com/blog-entry-72.html
  var fascii2ascii = (function() {
    var pattern = /[\uFF01-\uFF5E]/g,
      replace = function(m) {
        return String.fromCharCode(m.charCodeAt() - 0xFEE0);
      };
    return function(s) {
      return s.replace(pattern, replace);
    };
  })();

  var check = function(_val) {
    var val = fascii2ascii(_val).replace(/\D/g, '');
    if (val.length == 7) {
      if (cache[val] == undefined) {
        getAddr(val.replace(/(\d\d\d)(\d\d\d\d)/, '$1-$2'), function(json) {
          cache[val] = json;
          fillAddr(json);
        })
      } else {
        fillAddr(cache[val]);
      }
    }
  }

  this.each(function() {
    var elem = $(this);
    if (typeof target1 == 'object' && target1.zip2) {
      elem.add($(target1.zip2))
        .bind('keyup.zip2addr change.zip2addr', function() {
          check(elem.val() + '' + $(target1.zip2).val())
        })
        .bind('blur.zip2addr', function() {
          $(this).val(function() {
            return fascii2ascii($(this).val())
          })
        })
    } else {
      elem
        .bind('keyup.zip2addr change.zip2addr', function() {
          check(elem.val())
        })
        .bind('blur.zip2addr', function() {
          $(this).val(function() {
            return fascii2ascii($(this).val()).replace(/\D/g, '').replace(/(\d\d\d)(\d\d\d\d)/, '$1' + c.zipDelimiter + '$2')
          })
        })
    }
  });

  return this;
};

$.fn.zip2addr.cache = {};
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AddressApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <%# <script type="text/javascript" src="js/jquery.zip2addr.js"></script> %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if session[:planner_id] %>
        <%= link_to "イベント作成", events_new_path %>
        <%= link_to "ログアウト", "#" %>
  
        <%= Planner.find(session[:planner_id]).name %>

      <% else %>
        <%= link_to "ログイン", "/" %>
      <% end %>
      
    </header>
    <%= yield %>
  </body>
</html>

app/views/planners/new.html.erb
<h1>Planners#new</h1>
<p>Find me in app/views/planners/new.html.erb</p>
<%= form_for @planner, url: planner_create_path do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :password %>
  <%= f.text_field :password_confirmation %>
  <%= f.submit %>
<% end %>